site_name: Robot Guides
site_url: https://sooratilab.github.io/RobotGuides/
site_description: Guides for using the robots in B32.
site_author: SooratiLab
copyright: © 2025 SooratiLab

repo_url: https://github.com/sooratilab/robotguides
edit_uri: blob/main/docs/

# theme: mkdocs # readthedocs

theme:
  name: material
  # icon:
  #   admonition:
  #     note: octicons/tag-16
  #     abstract: octicons/checklist-16
  #     info: octicons/info-16
  #     tip: octicons/squirrel-16
  #     success: octicons/check-16
  #     question: octicons/question-16
  #     warning: octicons/alert-16
  #     failure: octicons/x-circle-16
  #     danger: octicons/zap-16
  #     bug: octicons/bug-16
  #     example: octicons/beaker-16
  #     quote: octicons/quote-16

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Report an Issue: report_an_issue.md
  - Go2:
      - Overview: go2/index.md
      - Getting Started: go2/getting_started.md
      - ROS2 Control: go2/ros_control.md
      - RGBD Camera: go2/rgbd_camera.md
      - External Lidar: go2/external_lidar.md
      - Troubleshooting: go2/troubleshooting.md
      - Useful Resources: go2/resources.md
      - 3D Models: go2/3d_models.md
  - TurtleBot3:
      - Overview: turtlebot3/index.md
      - Getting Started: turtlebot3/getting_started.md
      - Setup: turtlebot3/setup.md
      - ROS2 Control: turtlebot3/ros_control.md
      - Troubleshooting: turtlebot3/troubleshooting.md
      - Useful Resources: turtlebot3/resources.md
